name: yuque
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #网络请求
  dio: ^2.1.2
  #本地存储
  shared_preferences: ^0.5.2
  #Flare插件
  flare_flutter: ^1.5.5
  #状态管理
  provider: ^2.0.1
  #html展示
  flutter_html: ^0.10.1+hotfix.1
  #图片缓存
  cached_network_image: ^1.1.1
  #拖动图片
  photo_view: ^0.4.2
  #webview
  flutter_webview_plugin: ^0.3.5
  #极光推送
  jpush_flutter:
    git:
      url: https://github.com/CaiJingLong/jpush-flutter-plugin.git
      ref: 4d847f9b2150dc4fd1f8a7620d414d60f464fab7
  #刷新
  pull_to_refresh: ^1.4.5
  #获取app相关信息
  package_info: ^0.4.0+4
  #app目录
  path_provider: ^0.5.0+1
  #打开文件
  open_file: ^2.0.3
  #各种图标
  font_awesome_flutter: ^8.4.0
  #单元测试
  test: ^1.6.0


  #markdown
  # flutter_markdown: ^0.2.0
  #html样式
  flutter_widget_from_html_core: ^0.2.2
  flutter_widget_from_html: ^0.2.2+1
  # html2md: ^0.3.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

device_info: ^0.4.0+2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #导入下面目录下的各种资源
  assets:
    - flrs/
    - images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
